### ISSUE TITLE
Beta Note

### ISSUE THREAD

**Issue by julkascript** [julkascript/cardflow#128]
Add a note in the About page, which informs the user that the app is in a beta stage.

Text: The app is still in beta, some features may not be available! If you find any bugs, don’t hesitate to report them.

[Figma design](https://www.figma.com/design/GpsRZnN69f29pOCkiciWD4/Cardflow?node-id=2653-133&t=txQ0JRlo1Dw2NpLP-0)

**Comment by Alperadoss** [comment]
Hi, can you assign me to this issue? I'd like to do it

**Comment by julkascript** [comment]
@Alperadoss Hey, welcome, please feel free to pick up the ticket! Let me know if you need any assistance.
