### ISSUE TITLE
Add redirection to FAQ from Order modal

### ISSUE THREAD

**Issue by julkascript** [julkascript/cardflow#131]
Our Order system may be confusing to users. To provide help, add a new "Help" hyperlink button in the modal.

[Figma design](https://www.figma.com/design/GpsRZnN69f29pOCkiciWD4/Cardflow?node-id=1712-227&t=txQ0JRlo1Dw2NpLP-0)

**Comment by Alperadoss** [comment]
I'd like to solve this issue. Can you assign me?
