### ISSUE TITLE
Swap Order Modal information sequence

### ISSUE THREAD

**Issue by julkascript** [julkascript/cardflow#132]
To make the UI smoother, swap the table and summary places.

Also, align the "|" separators of the Summary and History sections to be on the same line.

<img width="1337" alt="image" src="https://github.com/julkascript/cardflow/assets/59143945/25a3bca5-f751-437d-a7d7-b93f5e1487d4">

**Comment by wyliemickelson** [comment]
I would like to try this

**Comment by RyotaMitaraiWeb** [comment]
> I would like to try this

this has been assigned to me already (and I almost done with it), feel free to check out an issue that has no assignees yet
