### ISSUE TITLE
Fix Checkout text color

### ISSUE THREAD

**Issue by julkascript** [julkascript/cardflow#133]
Change the Checkout button text color to be white.
Change the Checkout button text color to be black on hover.

This is how it's currently in prod:
<img width="1728" alt="image" src="https://github.com/julkascript/cardflow/assets/59143945/8205db2a-8357-4440-b771-0787d6c4bcf9">

**Comment by Alperadoss** [comment]
i'd like to solve it, can you assign me to issue?
