### ISSUE TITLE
Change searchbar placeholder text across Cardflow

### ISSUE THREAD

**Issue by julkascript** [julkascript/cardflow#148]
Change all searchbars' placeholder texts from "Type / to search" to "Search".

Old:
![image](https://github.com/user-attachments/assets/135f9f82-4e87-4dd5-abce-57c4c023b0ca)

New:
![image](https://github.com/user-attachments/assets/799f7478-b4d6-479d-ba6b-d06f9e0dd13b)

**Comment by amthomps11** [comment]
Hey! I'd love to work on this

**Comment by julkascript** [comment]
Heyo. I assigned it to you, have fun!
