### ISSUE TITLE
Accept button should be disabled when state is accepted

### ISSUE THREAD

**Issue by julkascript** [julkascript/cardflow#176]
When the current logged in user has accepted the offer - make the Accept button disabled.

![image](https://github.com/user-attachments/assets/fab016d7-2e16-4b4f-a3f7-2ccb938479f1)

**Comment by otutukingsley** [comment]
@julkascript please can i work on this issue? can you assign it to me? Thank you!

**Comment by julkascript** [comment]
> @julkascript please can i work on this issue? can you assign it to me? Thank you!

Please go ahead! Make sure you read the [CONTRIBUTING document](https://github.com/julkascript/cardflow/blob/develop/CONTRIBUTING.md), and don't hesitate to ask questions!
