### ISSUE TITLE
Allow searching for listings by card_set_id

### ISSUE THREAD

**Issue by RyotaMitaraiWeb** [julkascript/cardflow#32]
In order for #26 to dynamically render all current listings, the front end needs to be able to take all listings related to that card set. In other words, I would like to ask for a way to fetch all listings from ``/api/listing`` (or via a similar endpoint if you decide to create a new one for that purpose) whose ``card_set_id`` matches the requested one (assuming this functionality does not exist already and I am simply missing something)

**Example**
``/api/listing?card_set_id=2``

should return something like this:
```json
[
    {
      "id": 1,
      "card": 1,
      "card_name": "Accesscode Talker",
      "card_set_id": 2, // <- matching ID
      "user": 1,
      "user_name": "admin",
      "price": 1,
      "condition": "poor",
      "quantity": 9999,
      "is_listed": true,
      "is_sold": true
    },
    {
      "id": 2,
      "card": 1,
      "card_name": "Accesscode Talker",
      "card_set_id": 2, // <- matching ID
      "user": 1,
      "user_name": "admin",
      "price": 15,
      "condition": "excellent",
      "quantity": 12,
      "is_listed": true,
      "is_sold": false
    }
]
```
(obviously can be paginated and query string can be different, this is merely an example)

let me know if this is not feasible or if that's already possible to achieve and I am just missing something.

edit: changed up the second example a bit for consistency / clarity

**Comment by julkascript** [comment]
@milensski @dinocom33 guys, is the request clear for you? Can you pick it up?

**Comment by milensski** [comment]
@julkascript  @RyotaMitaraiWeb  I have made a PR for this, please check and let me know if something is missing or needs changing.

**Comment by RyotaMitaraiWeb** [comment]
Looks good to me (based on tinkering with it in Swagger, I got all results that I expected), great job with this and thanks for addressing it
