### ISSUE TITLE
Finish the purchase functionality

### ISSUE THREAD

**Issue by julkascript** [julkascript/cardflow#61]
1. (Frontend and Backend) Sellers should receive the sell request when a user buys their listing.
- "My sales" page, where the seller:
  - receives sell requests
  - can mark them as sent or rejected
  - Note: When the sell request has been marked as sent, the status of the order changes to "sent"
  - Note: When rejected - restore the numbers (status of order changes to "rejected")

2. (Frontend and Backend) Buyers should be able to track their purchase: see the state of the purchase (sent or not) and confirm if it's received
- Buyers have a "My orders" page, where they:
  - see their past orders listed, and their state
  - they can confirm an order that is in status "sent" -> order becomes "completed"
  - they can reject an order that is in status "sent" -> order becomes "rejected"
  - seller receives in his sell request list that the order is completed on the buyer's end
  - if the order has not been completed in 7 days, it becomes auto-completed

The `My orders` and `My sales` pages shall be accessed from the user dropdown, which is  implemented in #68.
Follow the Figma designs.

**Comment by julkascript** [comment]
Designs:

- [My sales](https://www.figma.com/file/GpsRZnN69f29pOCkiciWD4/Cardflow?type=design&node-id=1712-461&mode=design&t=gqWrWHsoq24z0YfN-0)
- [My sales modal](https://www.figma.com/file/GpsRZnN69f29pOCkiciWD4/Cardflow?type=design&node-id=1712-535&mode=design&t=gqWrWHsoq24z0YfN-0)

**Comment by julkascript** [comment]
@milensski @RyotaMitaraiWeb Guys, any movement here? Any difficulties?

**Comment by RyotaMitaraiWeb** [comment]
I have most of the UI ready and am just waiting for the backend so I can make it functional

**Comment by milensski** [comment]
I am done with the functionality, only the tests are missing and I am struggling with the auto complete job - not triggering

**Comment by julkascript** [comment]
> I am done with the functionality, only the tests are missing and I am struggling with the auto complete cron job - not triggering as expected

@milensski For me, it's okay if you already put the functionality on a PR. The "auto-complete" job we can do another time - it's not that important.

**Comment by milensski** [comment]
@julkascript @RyotaMitaraiWeb 
Perfect, I was also able to finish my tests today and created the PR.

Let me know what are your thoughts.
