### ISSUE TITLE
Save card pictures in the backend

### ISSUE THREAD

**Issue by julkascript** [julkascript/cardflow#65]
Save the pictures of the cards locally and serve as static images. According to [the API](https://ygoprodeck.com/api-guide/), if we do not do this, we may get banned by IP from using it.

**Comment by julkascript** [comment]
> @julkascript hi there, i would like to work on this, please assign this to me Thanks

Hey. Feel free to do so. But do you have the context? Do you need assistance?

**Comment by HyoungSooo** [comment]
Sure! thanks to @julkascript.
what should i do?

**Comment by julkascript** [comment]
> Sure! thanks to @julkascript. what should i do?

- Check out the [repository README](https://github.com/julkascript/cardflow/blob/develop/README.md) to see how to set up the project locally for development. 
- Also, check out the [contributing guidelines](https://github.com/julkascript/cardflow/blob/develop/CONTRIBUTING.md) to have some idea on how we contribute around here! 

Happy coding! Let me know if you need more help.
