### ISSUE TITLE
Create dev and prd modes for building

### ISSUE THREAD

**Issue by julkascript** [julkascript/cardflow#81]
The project should be able to be run with a “dev” configuration and a “prd” config.

**Comment by ZhivkoTringov** [comment]
I assume we need separate .env.prod for the frontend and the backend, Dockerfile.prod for the frontend and the backend, Docker-compose .prod.yml files.

**Comment by julkascript** [comment]
> I assume we need separate .env.prod for the frontend and the backend, Dockerfile.prod for the frontend and the backend, Docker-compose .prod.yml files.

Yes, correct. That is also how I see it.

**Comment by milensski** [comment]
The currently deployed version of the app is using the branch backend/gcp-deploy and the .env file is on the machine. Let me know if you need more info.
